### ISSUE TITLE
Workflow seems to crash when typing in multi-item delimiter

### ISSUE THREAD

**Issue by e28eta** [deanishe/alfred-fakeum#2]
I type in "fake Name ", and things look good. As soon as I type the DELIMITER character, the search resets back to "fake ".

If I instead type "fake Name  5", and then left arrow twice and add the DELIMITER, it works.

**Comment by deanishe** [comment]
Yeah. It's meant to do that. You're not supposed to enter the delimiter (which is why it's a character not on your keyboard) by hand but to hit TAB on one of the data types. That will complete the name and add the delimiter and a trailing space for you. (If you hit ENTER it will copy 1 fake dataset to your clipboard, CMD+ENTER will also paste the fake data into the active app).

If you delete the trailing space (i.e. the delimiter is the last thing in the query), the workflow treats that as a "go back" instruction and will take you back to the list of all datatypes.
